# PayTime Configuration
# Documentation: https://www.spigotmc.org/resources/paytime.107012/

# Price Settings
# Set the price for each time/weather change
# Use -1 to disable a specific change
prices:
  day: 10000
  night: 1000
  storm: 10000
  clear: 1000

# Message Settings
messages:
  # Plugin prefix (supports color codes)
  prefix: "&7[&6PayTime&7]&r"
  
  # Currency symbol (leave blank for no symbol)
  currency_symbol: "$"
  
  # Broadcast settings
  broadcast:
    enabled: true
    time: "&e%player%&r has paid to change the time to &e%time%."
    weather: "&e%player%&r has paid to change the weather to &e%weather%."
  
  # Error messages
  errors:
    not_enough_money: "&cYou do not have enough money to change the time."
    invalid_permission: "&cYou do not have permission to execute this command."
    already_day: "&cThe time is already day."
    already_night: "&cThe time is already night."
    already_clear: "&cThe weather is already clear."
    already_stormy: "&cThe weather is already stormy."
  
  # Success messages
  success:
    time_changed: "&aYou have paid %price% to change the time to &e%time%."
    weather_changed: "&aYou have paid %price% to change the weather to &e%weather%."
    config_reload: "&aConfiguration reloaded successfully."

# Time Settings
time:
  # Time values for day and night (in ticks)
  day: 0
  night: 14000

# Weather Settings
weather:
  # Duration of weather changes (in ticks)
  # Set to -1 for permanent changes
  duration: -1

# Feature Settings
features:
  # Enable/disable specific features
  time_changes: true
  weather_changes: true
  price_command: true
  reload_command: true

# Debug Settings
debug:
  # Enable debug mode for troubleshooting
  enabled: false
  # Log level (INFO, WARNING, SEVERE)
  log_level: "INFO"