name: PayTime
version: '${project.version}'
main: me.twistedactual.paytime.Main
api-version: '1.19'
description: A plugin that allows players to change time and weather in exchange for in-game currency.
author: TwistedActual
website: https://github.com/TwistedActual/PayTime
depend:
  - Vault
commands:
  paytime:
    description: Main command for PayTime
    usage: /paytime <day|night|storm|clear|price|reload|setprice|setduration|toggle>
    aliases: [pt]

permissions:
  paytime.day:
    description: Allows the player to change time to day
    default: true
  paytime.night:
    description: Allows the player to change time to night
    default: true
  paytime.storm:
    description: Allows the player to change weather to storm
    default: true
  paytime.clear:
    description: Allows the player to change weather to clear
    default: true
  paytime.price:
    description: Allows the player to view current prices
    default: true
  paytime.admin:
    description: Gives access to all admin commands
    default: op